server:
  port: 8083

spring:
  application:
    name: todo-api
  data:
    mongodb:
      uri: mongodb+srv://fahd:virus123m@cluster0.u1fysxi.mongodb.net/tododb?retryWrites=true&w=majority
  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: MySuperSecretKey
  expiration: 86400000
